import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    slug: 'career-launch-academy',
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: '🚀 Career Launch Academy - Complete PCMB 11th & 12th + Competitive Exams',
    rating: 5,
    ratingCount: 458,
    price: 34999,
    category: 'Career Launch Academy',
    tags: ['Comprehensive', 'All-in-One', 'Premium'],
    duration: '2 Years',
    instructor: 'Dr. Sharma & Team',
    featured: true,
    badge: 'Most Popular',
    students: 458,
  },
  {
    id: 2,
    slug: '11th-standard',
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'PCMB 11th Standard - Full Syllabus',
    rating: 5,
    ratingCount: 128,
    price: 15999,
    category: '11th Standard',
    tags: ['Board Prep', 'Comprehensive'],
    duration: '6 Months',
    instructor: 'Prof. Mehta',
    students: 128,
  },
  {
    id: 3,
    slug: '12th-standard',
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'PCMB 12th Board Preparation',
    rating: 5,
    ratingCount: 215,
    price: 18999,
    category: '12th Standard',
    tags: ['Board Prep', 'Advanced'],
    duration: '6 Months',
    instructor: 'Dr. Reddy',
    students: 215,
  },
  {
    id: 4,
    slug: 'neet',
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'NEET UG Complete Course',
    rating: 5,
    ratingCount: 178,
    price: 24999,
    category: 'Medical Entrance',
    tags: ['Medical', 'Comprehensive'],
    duration: '8 Months',
    instructor: 'Dr. Singh',
    students: 178,
  },
  {
    id: 5,
    slug: 'jee',
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'JEE Mains & Advanced',
    rating: 4,
    ratingCount: 162,
    price: 22999,
    category: 'Engineering Entrance',
    tags: ['Engineering', 'Advanced'],
    duration: '8 Months',
    instructor: 'Dr. Kumar',
    students: 162,
  },
  {
    id: 6,
    slug: 'kcet',
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'KCET Crash Course',
    rating: 4,
    ratingCount: 89,
    price: 12999,
    category: 'State Entrance',
    tags: ['Crash Course', 'Karnataka'],
    duration: '3 Months',
    instructor: 'Prof. Shetty',
    students: 89,
  },
  {
    id: 7,
    slug: '10th-standard',
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: '10th Standard Board Complete',
    rating: 5,
    ratingCount: 312,
    price: 11999,
    category: '10th Standard',
    tags: ['Board Prep', 'Complete'],
    duration: '5 Months',
    instructor: 'Mr. John',
    students: 312,
  },
  {
    id: 8,
    slug: 'test-series',
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'All Competitive Exams Mock Test Series',
    rating: 4,
    ratingCount: 156,
    price: 4999,
    category: 'Test Series',
    tags: ['Mock Tests', 'Practice'],
    duration: '6 Months',
    instructor: 'Expert Panel',
    students: 156,
  },
]