import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'PCMB 11th Standard - Full Syllabus',
    rating: 5,
    ratingCount: 128,
    price: 15999,
    category: '11th Standard',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'PCMB 12th Board Preparation',
    rating: 5,
    ratingCount: 215,
    price: 18999,
    category: '12th Standard',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'NEET UG Complete Course',
    rating: 4,
    ratingCount: 178,
    price: 24999,
    category: 'Medical Entrance',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'JEE Mains & Advanced',
    rating: 4,
    ratingCount: 162,
    price: 22999,
    category: 'Engineering Entrance',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'KCET Crash Course',
    rating: 4,
    ratingCount: 89,
    price: 12999,
    category: 'State Entrance',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: '10th Standard Board Complete',
    rating: 5,
    ratingCount: 312,
    price: 11999,
    category: '10th Standard',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'All Competitive Exams Mock Test Series',
    rating: 4,
    ratingCount: 156,
    price: 4999,
    category: 'Test Series',
  },
]